apiVersion: v1
kind: Service
metadata:
  name: challenges
  namespace: insurance
  labels:
    app: challenges
  annotations:
    prometheus.io/scrape: 'true'    
    prometheus.io/port: '5555'
spec:
  selector:
    app: challenges
    component: msr
  ports:
    - port: 5555
      name: http-server
      targetPort: 5555
      nodePort: 30301
  type: NodePort
  sessionAffinity: ClientIP