kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: solution-msr
  namespace: kplogesh-dev
  labels:
    app: solution-msr
spec:
  host: 
  to:
    kind: Service
    name: solution-msr
    weight: 100
  port:
    targetPort: http-server
  tls:
    termination: edge
  wildcardPolicy: None