apiVersion: v1
kind: Service
metadata:
  name: solution-msr
  namespace: kplogesh-dev
  labels:
    app: solution-msr
spec:
  selector:
    app: solution-msr
    component: msr
  ports:
    - port: 5555
      name: http-server
      targetPort: 5555
  type: ClusterIP
  sessionAffinity: ClientIP