apiVersion: v1
kind: ConfigMap
metadata:
  name: c3
  labels:
    app: challenges
    version: v1.0
data:
  application2.properties: |
    globalvariable.mem123123_customer_url.value=http\://api-gateway\:5555/gateway/customers/1.0/customers123
