# Default values for microservicesruntime.

# -- Number of replicates in Deployment
replicaCount: 1

image:
  # -- Pull this image. Default is MSR from [Software AG Container Registry](https://containers.softwareag.com)
  repository: "sagcr.azurecr.io/webmethods-microservicesruntime"
  # -- Pull with policy
  pullPolicy: IfNotPresent
  # -- The default value pulls latest. In PROD it is recommended to use a specific fix level.
  tag:        "10.15"

# -- Image pull secret reference. By default looks for `regcred`.
imagePullSecrets: 
  - name: regcred

revisionHistoryLimit: 2

checksum: false