apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: fitness-build-run
  namespace: kplogesh-dev
spec:
  pipelineRef:
    name: solution-build
  params:
    - name: REPO_URL
      value: 'https://github.com/kplogesh/openshift.git'
    - name: IMAGE_NAME
      value: 'msr-test'
    - name: IMAGE_TAG
      value: 'latest'
    - name: NAMESPACE
      value: 'default'
