apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-deploy
  namespace: kplogesh-dev
spec:
  params:
    - default: 'https://github.com/kplogesh/openshift.git'
      description: Repository URL
      name: REPO_URL
      type: string
    - default: 'msr-test'
      description: 'MSR Test'
      name: IMAGE_NAME
      type: string
  tasks:
    - name: build-container
      taskRef:
        kind: Task
        name: build-container