apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: fitness-build
  namespace: kplogesh-dev
spec:
  params:
    - default: 'https://github.com/kplogesh/openshift.git'
      description: Repository URL
      name: REPO_URL
      type: string
    - default: 'msr-test'
      description: 'MSR Test'
      name: IMAGE_NAME
      type: string
    - default: latest
      description: 'Image Tag'
      name: IMAGE_TAG
      type: string
    - default: default
      description: 'Namespace'
      name: NAMESPACE
      type: string
  tasks:
    - name: fitness-build-container
      taskRef:
        kind: Task
        name: fitness-build-container