apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: solution-build-task
  namespace: kplogesh-dev
spec:
  params:
    - default: 'https://github.com/kplogesh/openshift.git'
      description: Repository URL
      name: REPO_URL
      type: string
    - default: 'master'
      description: Repository URL
      name: REPO_REF
      type: string
    - default: 'msr-test'
      description: 'MSR Test'
      name: IMAGE_NAME
      type: string
    - default: latest
      description: 'Image Tag'
      name: IMAGE_TAG
      type: string
    - default: kplogesh-dev
      description: 'Namespace'
      name: NAMESPACE
      type: string
  steps:
    - name: fetch-repository
      image: alpine/git
      script: |
        git clone --recursive $(inputs.params.REPO_URL) /workspace/source
    - name: apply-solution-buildconfig
      image: openshift/origin-cli
      workingDir: /workspace/source
      script: |
        echo Applying manifests -----
        # Create the imagestream
        oc process -f buildconfig/imagestream-template.yaml -p IMAGE_NAME=$(inputs.params.IMAGE_NAME) | oc apply -f -

        # Create the BuildConfig
        oc process -f buildconfig/buildconfig-template.yaml -p REPO_URL=$(inputs.params.REPO_URL) -p REPO_REF=$(inputs.params.REPO_REF) -p IMAGE_NAME=$(inputs.params.IMAGE_NAME) -p IMAGE_TAG=$(inputs.params.IMAGE_TAG) | oc apply -f -
    - name: start-solution-build 
      image: openshift/origin-cli
      script: |
        oc start-build solution-buildconfig