apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: solution-ut-pipeline
  namespace: kplogesh-dev
spec:
  params:
    - default: 'https://bitbucket.org/kplogesh/ctr-integration-contract.git'
      description: Repository URL
      name: CTR_REPO_URL
      type: string
    - default: 'main'
      description: Repository URL
      name: CTR_REPO_REF
      type: string
    - default: 'https://bitbucket.org/kplogesh/wmdevops.git'
      description: Repository URL
      name: DEVOPS_REPO_URL
      type: string
    - default: 'main'
      description: Repository URL
      name: DEVOPS_REPO_REF
      type: string
    - default: 'image-registry.openshift-image-registry.svc:5000/kplogesh-dev/sag-install-base'
      description: 'Installer Image used to generate for MSR'
      name: INSTALLER_IMAGE_NAME
      type: string
    - default: latest
      description: 'Installer Image Tag'
      name: INSTALLER_IMAGE_TAG
      type: string
    - default: 'image-registry.openshift-image-registry.svc:5000/kplogesh-dev/test-infra-wpx'
      description: 'WPX Image'
      name: WPX_IMAGE_NAME
      type: string
    - default: latest
      description: 'WPX Image Tag'
      name: WPX_IMAGE_TAG
      type: string
    - default: kplogesh-dev
      description: 'Namespace'
      name: NAMESPACE
      type: string
  tasks:
    - name: solution-ut-task
      taskRef:
        kind: Task
        name: solution-ut-task
      params:
      - name: CTR_REPO_URL
        value: $(params.CTR_REPO_URL)
      - name: CTR_REPO_REF
        value: $(params.CTR_REPO_REF)
      - name: DEVOPS_REPO_URL
        value: $(params.DEVOPS_REPO_URL)
      - name: DEVOPS_REPO_REF
        value: $(params.DEVOPS_REPO_REF)
      - name: INSTALLER_IMAGE_NAME
        value: $(params.INSTALLER_IMAGE_NAME)
      - name: INSTALLER_IMAGE_TAG
        value: $(params.INSTALLER_IMAGE_TAG)
      - name: WPX_IMAGE_NAME
        value: $(params.WPX_IMAGE_NAME)
      - name: WPX_IMAGE_TAG
        value: $(params.WPX_IMAGE_TAG)
      - name: NAMESPACE
        value: $(params.NAMESPACE)