apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: fitness-build-container
  namespace: kplogesh-dev
spec:
  params:
    - default: 'https://github.com/kplogesh/openshift.git'
      description: Repository URL
      name: REPO_URL
      type: string
    - default: 'msr-test'
      description: 'MSR Test'
      name: IMAGE_NAME
      type: string
    - default: latest
      description: 'Image Tag'
      name: IMAGE_TAG
      type: string
  steps:
    - name: git-source
      image: alpine/git
      script: |
        git clone --recursive $(inputs.params.REPO_URL) /workspace/source
        ls -l /workspace/source/buildconfig
    - name: apply-fitness-buildconfig
      image: openshift/origin-cli
      script: |
        cd /workspace/source
        # Apply the ImageStream configuration
        oc apply -f buildconfig/imagestream.yaml

        # Apply the BuildConfig configuration
        oc apply -f buildconfig/buildconfig.yaml
    - name: start-fitness-build 
      image: openshift/origin-cli
      script: |
        cd /workspace/source
        oc start-build fitness-buildconfig