extraConfigMaps:
  int-cfg:
    automount: true
    automountDir: /opt/softwareag/IntegrationServer/msr-cfg
    data:
      test.properties: |
        globalvariable.mem123123_customer_url.value=http\://api-gateway\:5555/gateway/customers/1.0/customers1235446

secrets:
  msr-secrets:
    automount: true
    automountDir: /etc/secrets
    kind: Secret
    type: Opaque 
    stringData:
      secret.properties: |
        username: test
        password: test
        another: another
      

# -- Secret mounts, A list of secrets and their paths to mount inside the pod
#secretMounts: 
#  - name: msr-secrets
#    path: /etc/secrets

# -- Secret volumes, A list of secrets
#secretVolumes: 
#  - name: msr-secrets
#    secretName: msr-secrets