extraFiles:
  - name: solution-file-pkg1
    data:
      solution-file-pkg1.csv: |
        a,b,c
        b,c,d,e
  - name: solution-file-pkg2
    data:
      solution-file-pkg2.csv: |
        a,b,c
        b,c,d,e