apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: fitness-buildconfig
spec:
  runPolicy: Serial
  source:
      git:
        ref: master
        uri: https://github.com/kplogesh/openshift
      type: Git
  strategy:
      dockerStrategy:
      type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: fitness-msr:1.0.0
  triggers:
    - type: ConfigChange
