kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: solution-imagestreamtag-template
objects:
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: ${IMAGE_NAME}
parameters:
  - name: IMAGE_TAG
    displayName: Image Tag
    description: Image Tag
    value: ${IMAGE_TAG}
    required: true 
  - name: IMAGE_NAME
    displayName: Image Name
    description: Image Name
    value: ${IMAGE_NAME}
    required: true 
message: "... Successful ..." 