apiVersion: tekton.dev/v1
kind: ClusterTask
metadata:
  name: docker-build-cluster-task
spec:
  podTemplate:
    volumes:
      - name: varlibdocker
        emptyDir: {}
    containers:
      - name: docker-container
        image: docker:latest
        command:
          - /bin/sh
          - -c
        args:
          - |
            docker build -t docker-app-image:latest .
        volumeMounts:
          - name: varlibdocker
            mountPath: /var/lib/docker
  securityContext:
    privileged: true
